### ISSUE TITLE
Niimath usage for creating ventricle distancemap

### ISSUE THREAD

**Issue by dilekozkan** [rordenlab/niimath#22]
Hello,
I generated a binary ventricle mask from T1 image.
I need to create a distance map from the ventricles using FSL distancemap, it is too slow as you said.
Can I use 'niimath vetnriclemask.nii.gz -edt dxInVM’ for this aim? Is my command true? (Otherwise; niimath vetnriclemask.niig.z -binv -edt dxFromVM
mybinary ventricle mask : ventricles:1 the remaining area:0
FSLdistance map output’s definition is = where the intensity of each voxel represent its distance in mm from the ventricles mask

Best

**Comment by ofgulban** [comment]
Hi @dilekozkan ,

I happen to see this issue, and although I do not use FSL distancemap or its niimath equivalent, I happen to have distance computation program (see [LayNii](https://github.com/layerfMRI/LAYNII) package `LN2_GEODISTANCE` program).

For instance, just to quickly test, I have grabbed a WM segmentation and computed distances to form the WM to the rest of the image. My image was a 512x512x512 voxels 0.5mm whole brain image. Here are the commands I have used (also attaching my file [wm.nii.gz](https://github.com/rordenlab/niimath/files/11295812/wm.nii.gz)
):

```
niimath wm.nii.gz -binv -dilF wm_inv.nii.g

LN2_GEODISTANCE -init wm.nii.gz -domain wm_inv.nii.gz -output wm_distances.nii.gz
```

Picture below shows the distances  and the wm and wm_inv images. This wm binary image should be similar to your ventricle binary mask.
![Screenshot_2023-04-21_14-39-20](https://user-images.githubusercontent.com/4668327/233638968-9ac8bab0-8219-459f-b9ee-73d2f240ced9.png)

Computation took ~4 minutes on 4 years old PC with a decent CPU. Distances are computed in the every voxel within the red areas (geodesically, not euclidean distances). I am not sure what is the size of your data or specifics of your hardware, but maybe this can help in some way.


NOTE: @neurolabusc , very cool extension of fslmaths. I am using niimath more and more, especially because it is so easy to install on different machines. Kudos.

**Comment by neurolabusc** [comment]
@ofgulban since we both use BSD licenses, you are free to adapt my [euclidean distance transform nifti_edt()](https://github.com/rordenlab/niimath/blob/f644a9738ed1f014acd39818dae153f7a6f225e3/src/coreFLT.c#L444) to your [LN2_GEODISTANCE](https://github.com/layerfMRI/LAYNII/blob/858a32fc2260a3ba8767c095e58a7ab6f72ecbf0/src/LN2_GEODISTANCE.cpp). Alternatively, [afni_edt()](https://github.com/afni/afni/blob/aed6e36a6fbb4966dfd86611e039fa8dee828114/src/thd_depth.c#L224) will give identical results. It is unintuitive that this process is separable, [](https://prideout.net/blog/distance_fields/). It is elegantly described [here](https://prideout.net/blog/distance_fields/). Feel free to pick and copy niimath functions or just add it as a dependency. I do know that future versions of FSL are adopting this algorithm.

**Comment by ofgulban** [comment]
Cool, thanks for the pointers @neurolabusc :) !
