### ISSUE TITLE
2D dog option?

### ISSUE THREAD

**Issue by hanayik** [rordenlab/niimath#5]
@neurolabusc, what do you think of a 2D dog option to niimath? I think it might be useful in cases where slice thickness in a particular plane is large (e.g. 5 mm or thicker) and edges in that direction are less useful since they are blurred across large regions of the image.

**Comment by neurolabusc** [comment]
@hanayik I extended the code to support DoG for 2D images (e.g. volumes with only one slice in the x,y,z direction). I have also allowed the user to specify whether DoG should be applied in three dimensions or only two. I just need to come up with the command line interface terminology, e.g. `dogx`, `dogy` and `dogz` to apply to 2D sagittal (where slice is the x/i dimension), coronal (y,j), axial (z,k).

The typical usage may not be for anisotropic data, for example [FSL](https://github.com/neurolabusc/coreg_qa) applies slicer after reslicing low resolution (sometime anisotropic) EPI data to match the resolution of high-resolution structural scans (typically isotropic).

Rather, users may prefer a 2D slicing when they want to generate 2D bitmaps. The two images below show the 3D DoG (top) and 2D DoG (bottom). The 3D DoG appears fat at locations where the edge is oblique rather than orthogonal to the slice. The 2D DoG keeps single-pixel thick lines (though it would show gaps if you showed coronal or axial cuts).
 
![mosaic](https://user-images.githubusercontent.com/8930807/136694631-714f18f7-623e-45f4-8f6d-408e8b6948b1.png)

![2Dmosaic](https://user-images.githubusercontent.com/8930807/136695526-ee1e5175-fd47-4bcc-b050-a7630bc9ce8c.png)

As an aside, I do want to say that DoG and AFNI's [3dedge3](https://github.com/neurolabusc/coreg_qa) dramatically outperform FSL's slicer. Here is an [slicer output](https://www.biorxiv.org/content/10.1101/590521v1.full) from an original version of an article, not surprising the authors later updated the figure to not use Slicer.

![F2 large](https://user-images.githubusercontent.com/8930807/136695812-21c59b7d-7f8b-4db7-a489-1d2d0053a676.jpg)

**Comment by neurolabusc** [comment]
To illustrate, same edges shown in coronal plane. The lines remain coherent (if blocky) in the 3D DoG, but look disjointed for the sagittal 2D (`dogx`) sliced coronally (where slices are the `y` dimension).
![2DmosaicCOLD](https://user-images.githubusercontent.com/8930807/136696175-ea1693dc-8ed1-4753-9b9a-e3729ed54c14.png)
![2DmosaicC](https://user-images.githubusercontent.com/8930807/136696177-977ad364-e6d7-496b-9cf1-955d6fc18a5e.png)
