### ISSUE TITLE
Missing Linux binaries

### ISSUE THREAD

**Issue by effigies** [rordenlab/niimath#6]
Just a note that your README indicates there should be Linux binaries at https://github.com/rordenlab/niimath/releases/latest/download/niimath_lnx.zip

Pleasantly smooth to compile locally, so this is not an urgent issue.

**Comment by neurolabusc** [comment]
@effigies good point. I will keep this issue open until the next stable release which will include a downloadable executable.

**Comment by neurolabusc** [comment]
@effigies fixed with [v1.0.20211212](https://github.com/rordenlab/niimath/releases). The compiled Linux download is generated with [holy build box](https://github.com/FooBarWidget/holy-build-box). This should provide a universal (though unoptimized) executable. Please test and close issue if you agree this addresses your comments.
